name: Build
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Download bob.jar
        run: |
          curl -LO https://github.com/defold/defold/releases/download/1.9.0/bob.jar

      - name: Execute bob.jar
        run: java -jar bob.jar
