name: Publish

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: Bird
          directory: build
          githubToken: ${{ secrets.GITHUB_TOKEN }}